import "server-only"

import { z } from "zod"
import type { UIMessage } from "ai"

/**
 * Structured portfolio response contract — the one place that defines what
 * the assistant is allowed to attach to an answer beyond plain text.
 *
 * This is deliberately *not* generated by the model (no `Output.object` /
 * `generateObject` JSON mode). The model keeps answering with ordinary
 * streamed Markdown text exactly as before; `response-builder.ts` assembles
 * this payload mechanically from the same tool-call results that already
 * ground the answer, then this schema validates the assembled object before
 * it's sent to the client. See the trade-off note in `response-builder.ts`
 * for why: it keeps text streaming untouched, and it makes it structurally
 * impossible for the model to invent an evidence URL or a skill that wasn't
 * actually returned by a tool.
 */

export const MAX_EVIDENCE_ITEMS = 3
export const MAX_SKILL_CHIPS = 5
export const MAX_SUGGESTED_QUESTIONS = 3

export const evidenceTypeSchema = z.enum(["project", "experience", "skill", "lab"])
export const evidenceLevelSchema = z.enum(["professional", "project", "demonstrated", "learning"])
export const skillStatusSchema = z.enum(["primary", "working-knowledge", "learning"])

export const evidenceItemSchema = z.object({
    type: evidenceTypeSchema,
    title: z.string().min(1),
    description: z.string().optional(),
    /** Internal portfolio path only (e.g. "/projects/h-phsar") — never an invented or external URL. */
    href: z.string().startsWith("/").optional(),
    evidenceLevel: evidenceLevelSchema,
})

export const skillChipSchema = z.object({
    name: z.string().min(1),
    status: skillStatusSchema,
})

/** The side-channel payload attached to an assistant message (everything except the answer text, which streams as normal message text). */
export const portfolioAssistantMetaSchema = z.object({
    evidence: z.array(evidenceItemSchema).max(MAX_EVIDENCE_ITEMS),
    skills: z.array(skillChipSchema).max(MAX_SKILL_CHIPS),
    suggestedQuestions: z.array(z.string().min(1)).max(MAX_SUGGESTED_QUESTIONS),
})

/** Full contract (answer text + meta) — used by eval/test code that wants to assert on a complete response, not by the runtime request path. */
export const portfolioAssistantResponseSchema = portfolioAssistantMetaSchema.extend({
    answer: z.string().min(1),
})

export type EvidenceType = z.infer<typeof evidenceTypeSchema>
export type EvidenceLevel = z.infer<typeof evidenceLevelSchema>
export type SkillStatus = z.infer<typeof skillStatusSchema>
export type EvidenceItem = z.infer<typeof evidenceItemSchema>
export type SkillChip = z.infer<typeof skillChipSchema>
export type PortfolioAssistantMeta = z.infer<typeof portfolioAssistantMetaSchema>
export type PortfolioAssistantResponse = z.infer<typeof portfolioAssistantResponseSchema>

/** Custom UI data-part map for the assistant's messages — one part, `data-portfolio`, carrying `PortfolioAssistantMeta`. */
export type PortfolioUIMessage = UIMessage<unknown, { portfolio: PortfolioAssistantMeta }>

export const EMPTY_PORTFOLIO_META: PortfolioAssistantMeta = { evidence: [], skills: [], suggestedQuestions: [] }

/** True when there's anything worth attaching — an all-empty payload should never be sent (see rule: not every answer needs cards). */
export function hasPortfolioMeta(meta: PortfolioAssistantMeta): boolean {
    return meta.evidence.length > 0 || meta.skills.length > 0 || meta.suggestedQuestions.length > 0
}
